name: Build, test & lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # 1️⃣ Ephemeral Postgres for the job
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fastapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # 2️⃣ Env vars your Settings class expects
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: fastapi_test
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SECRET_KEY: changeme
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary pytest

      # Optional: run Alembic or your own init script
      - name: Run migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest -q
